version: 0.1

phases:
  install:
    commands:
      - echo Installing yarn...
      - npm install yarn -g
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn build
      - echo Copying files to s3
      - aws s3 sync ./public s3://calendarcounter.ryanpfister.com/ --delete --acl public-read --metadata-directive REPLACE --cache-control max-age=2592000,public
      - echo Copying .html to s3 separately to set 0 max-age
      - aws s3 cp ./public s3://calendarcounter.ryanpfister.com/ --recursive --exclude "*" --include "*.html" --acl public-read --metadata-directive REPLACE --cache-control max-age=0,public
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "build"
